### ISSUE TITLE
Add new throughput curves page

### ISSUE THREAD

**Issue by tddesjardins** [spacetelescope/acs-notebook#5]
Replace http://www.stsci.edu/hst/acs/analysis/throughputs with a notebook. 
Add new page with throughput curve example shown. Make sure it re-creates all of the plots on the page dynamically, so they are the most up to date possible.

If we do this, we may want to move the downloadable throughput files to another page similar to the ACS aperture corrections page and then just link to it. Unless we want the notebook to make these files on the fly or replace them in some other manner. @nmiles2718 any thoughts?

**Comment by tddesjardins** [comment]
Also, do we want to maybe merge the bandwidth information with this page into one "ACS Filters" notebook/webpage?

**Comment by nmiles2718** [comment]
Coincidentally, I started working on this last night. The [Throughputs page](http://www.stsci.edu/hst/acs/analysis/throughputs) is much less involved than the [Zeropoints page](http://www.stsci.edu/hst/acs/analysis/zeropoints) and the biggest change we would make is to incorporate interactive plots of the filter bandpasses.
 
I think there are three ways to go about this:
1.  Create a notebook with interactive `bokeh` plots, export the notebook to `html` with `nbconvert` and finally copy and paste the `html` into `Zope`
2.  Create interactive plots in `bokeh` and use `file_html()` to generate an `html` string that is a version of the plot which can be embedded into a webpage. I have tested this already, and it was very straightforward to do
3.  Create interactive plots using `matplotlib` and `mpld3`, see [this example](http://mpld3.github.io/examples/interactive_legend.html).

I am in favor of option 3 because of my familiarity with `matplotlib` and the level of maturity of `mpld3`. The `mpld3` package appears to have all of the same functionality as `bokeh`, plus it was written by Jake Vanderplas, so you know it's good. The only downside is that it is not actively maintained. 👎

**Comment by tddesjardins** [comment]
@nmiles2718 given changes to the ACS webpages coming up, did we want to include a notebook that contains the throughput plots?

**Comment by nmiles2718** [comment]
@tddesjardins I dont think this is necessary anymore. I have the interactive plots currently up on the new webpage within Jahia. Rather than recreating the ACS webpage, it would be more instructive to do a generalized example with `pysynhot` in a small code block on the website just above the interactive plots. I vote to close this issue.

**Comment by tddesjardins** [comment]
Sounds good! I wasn't sure if you got the plots working or not after our conversations about Jahia limitations, but if that's working then I agree.
